// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Flavor Mobile Brand Provisioning Tool

import 'package:flutter/material.dart';

abstract class BrandTokens {
  static const String appName = 'رستوران شاندیز';
  static const String tenantId = 'test_shandiz';
  static const String apiBaseUrl = 'https://demo.flavor.restaurant/wp-json/flavor/v1';
  static const int defaultBranchId = 1;

  static const Color primaryColor = Color(0xFFD32F2F);
  static const Color secondaryColor = Color(0xFF388E3C);
  static const Color accentColor = Color(0xFFFBC02D);

  static const String supportPhone = '021-99999999';
  static const String supportEmail = 'info@shandiz.com';
  static const String privacyPolicyUrl = 'https://shandiz.com/privacy';
  static const String termsUrl = 'https://shandiz.com/terms';
}
