// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Flavor Mobile Brand Provisioning Tool

import 'package:flutter/material.dart';

abstract class BrandTokens {
  static const String appName = 'Flavor Restaurant';
  static const String tenantId = 'default_tenant';
  static const String apiBaseUrl = 'https://restaurant.example.com/wp-json/flavor/v2';
  static const int defaultBranchId = 0;

  static const Color primaryColor = Color(0xFFC62828);
  static const Color secondaryColor = Color(0xFF2E7D32);
  static const Color accentColor = Color(0xFFFFA000);

  static const String supportPhone = '021-88888888';
  static const String supportEmail = 'support@flavor.restaurant';
  static const String privacyPolicyUrl = '';
  static const String termsUrl = '';
}
