<?php
/**
 * Eight importable demo packs. Prices are Toman.
 *
 * @package Flavor
 */

defined( 'ABSPATH' ) || exit;

/**
 * Build a menu item row.
 *
 * @param string               $name Name.
 * @param string               $desc Description.
 * @param int                  $price Toman.
 * @param string               $cat Category slug.
 * @param array<string, mixed> $extra Extra.
 * @return array<string, mixed>
 */
function flavor_demo_item( string $name, string $desc, int $price, string $cat, array $extra = array() ): array {
	return array_merge(
		array(
			'name'        => $name,
			'description' => $desc,
			'price'       => $price,
			'category'    => $cat,
			'prep'        => 15,
			'modifiers'   => array(),
			'dietary'     => array(),
			'schedule'    => array(),
		),
		$extra
	);
}

/**
 * All demos.
 *
 * @return array<string, array<string, mixed>>
 */
function flavor_demo_catalog(): array {
	$size = array(
		array( 'type' => 'size', 'name' => 'کوچک', 'price' => 0, 'is_default' => 1 ),
		array( 'type' => 'size', 'name' => 'بزرگ', 'price' => 25000, 'is_default' => 0 ),
	);

	return array(
		'modern-cafe'   => array(
			'slug'         => 'modern-cafe',
			'title'        => 'کافه مدرن',
			'site_title'   => 'کافه نوژا',
			'tagline'      => 'قهوه تخصصی، فضای آرام',
			'hero_title'   => 'یک فنجان دقیق، یک بعدازظهر آرام',
			'hero_text'    => 'دانه‌های تازه برشته، شیر گیاهی و شیرینی‌های خانگی در قلب تهران.',
			'about'        => 'کافه نوژا از ۱۳۹۸ با تمرکز روی قهوه تخصصی و فضای کار دوستانه فعالیت می‌کند. هر فنجان با ترازو و زمان‌سنج آماده می‌شود.',
			'branch_name'  => 'شعبه ولیعصر',
			'city'         => 'تهران',
			'phone'        => '02188001234',
			'address'      => 'ولیعصر، بالاتر از پارک‌وی',
			'categories'   => array( 'قهوه' => 'coffee', 'چای و دمنوش' => 'tea', 'صبحانه' => 'breakfast', 'شیرینی' => 'pastry' ),
			'testimonials' => array(
				array( 'name' => 'سارا محمدی', 'text' => 'لاته‌شان پایدارترین فومی است که در تهران خوردم.' ),
				array( 'name' => 'کیان رضایی', 'text' => 'برای کار با لپ‌تاپ عالی است؛ پریز و وای‌فای پایدار.' ),
			),
			'items'        => array(
				flavor_demo_item( 'اسپرسو', 'شات دوبل از ترکیب برزیل و اتیوپی', 45000, 'coffee' ),
				flavor_demo_item( 'آمریکانو', 'اسپرسو و آب داغ', 55000, 'coffee' ),
				flavor_demo_item( 'لاته', 'اسپرسو و شیر بافت‌دار', 75000, 'coffee', array( 'modifiers' => $size ) ),
				flavor_demo_item( 'کاپوچینو', 'نسبت کلاسیک یک‌سوم', 72000, 'coffee' ),
				flavor_demo_item( 'موکا', 'شکلات تلخ ۷۰ درصد', 82000, 'coffee' ),
				flavor_demo_item( 'فلت‌وایت', 'بافت مخملی، فنجان کوچک', 78000, 'coffee' ),
				flavor_demo_item( 'آیس لاته', 'روی یخ، شیر به انتخاب شما', 80000, 'coffee', array( 'modifiers' => $size ) ),
				flavor_demo_item( 'هات‌چاکلت', 'شکلات بلژیکی', 70000, 'coffee' ),
				flavor_demo_item( 'چای ماسالا', 'ادویه تازه سابیده‌شده', 65000, 'tea' ),
				flavor_demo_item( 'چای ترش', 'چای ترش و دارچین', 50000, 'tea' ),
				flavor_demo_item( 'دمنوش بابونه', 'آرام‌بخش شب', 48000, 'tea' ),
				flavor_demo_item( 'گرانولا و ماست', 'عسل گون و توت خشک', 95000, 'breakfast', array( 'dietary' => array( 'vegetarian' ), 'schedule' => array( 'breakfast' ) ) ),
				flavor_demo_item( 'املت اسفناج', 'نان خمیرترش', 110000, 'breakfast', array( 'dietary' => array( 'vegetarian' ), 'schedule' => array( 'breakfast' ) ) ),
				flavor_demo_item( 'اووکادو تست', 'تخم‌مرغ نیمرو و دانه کنجد', 125000, 'breakfast', array( 'schedule' => array( 'breakfast' ) ) ),
				flavor_demo_item( 'کرواسان کره‌ای', 'پخت صبح', 55000, 'pastry' ),
				flavor_demo_item( 'چیزکیک نیویورکی', 'برش تازه', 85000, 'pastry' ),
				flavor_demo_item( 'براونی گردو', 'کاکائو تلخ', 65000, 'pastry' ),
				flavor_demo_item( 'کوکی شکلات', 'نیمه‌پز، گرم', 40000, 'pastry' ),
				flavor_demo_item( 'ساندویچ بوقلمون', 'نان چاباتا و خردل عسل', 145000, 'breakfast' ),
				flavor_demo_item( 'سالاد کینوا', 'انار، فتا، نعنا', 135000, 'breakfast', array( 'dietary' => array( 'vegetarian' ) ) ),
				flavor_demo_item( 'اسموتی توت', 'موز و شیر بادام', 90000, 'coffee', array( 'dietary' => array( 'vegan' ) ) ),
				flavor_demo_item( 'آب پرتقال تازه', 'پرس سرد', 60000, 'tea' ),
			),
		),
		'fast-food'     => array(
			'slug'         => 'fast-food',
			'title'        => 'فست‌فود',
			'site_title'   => 'برگر فایو',
			'tagline'      => 'سریع، داغ، حسابی',
			'hero_title'   => 'برگر اسمش، سیب‌زمینی دوبل',
			'hero_text'    => 'سفارش در کمتر از ده دقیقه. کمبوهای خانواده و سس خانه.',
			'about'        => 'برگر فایو روی گوشت تازه روزانه و نان بریوش خانگی تمرکز دارد. شعبه سعادت‌آباد برای بیرون‌بر و ارسال بهینه شده.',
			'branch_name'  => 'شعبه سعادت‌آباد',
			'city'         => 'تهران',
			'phone'        => '02122110011',
			'address'      => 'سعادت‌آباد، سرو غربی',
			'categories'   => array( 'برگر' => 'burger', 'مرغ' => 'chicken', 'پیش‌غذا' => 'sides', 'نوشیدنی' => 'drinks' ),
			'testimonials' => array(
				array( 'name' => 'امیر حسینی', 'text' => 'چیزبرگر دوبل ارزش قیمتش را دارد.' ),
				array( 'name' => 'نرگس کاظمی', 'text' => 'ارسال بیست دقیقه‌ای برای ناهار اداری عالی بود.' ),
			),
			'items'        => array(
				flavor_demo_item( 'اسمش برگر', 'گوشت ۱۴۰ گرم، پنیر چدار', 185000, 'burger', array( 'modifiers' => array( array( 'type' => 'topping', 'name' => 'بیکن', 'price' => 35000 ), array( 'type' => 'topping', 'name' => 'تخم‌مرغ', 'price' => 20000 ) ) ) ),
				flavor_demo_item( 'چیزبرگر کلاسیک', 'سس مخصوص خانه', 165000, 'burger' ),
				flavor_demo_item( 'دابل برگر', 'دو لایه گوشت', 245000, 'burger' ),
				flavor_demo_item( 'برگر گیاهی', 'پتی لوبیا و قارچ', 175000, 'burger', array( 'dietary' => array( 'vegetarian' ) ) ),
				flavor_demo_item( 'چیکن برگر', 'فیله سوخاری', 155000, 'chicken' ),
				flavor_demo_item( 'مرغ سوخاری ۳ تکه', 'ادویه جنوب', 210000, 'chicken' ),
				flavor_demo_item( 'ناگت ۱۰ تکه', 'سس باربیکیو', 125000, 'chicken' ),
				flavor_demo_item( 'فیله استریپس', 'چهار تکه', 145000, 'chicken' ),
				flavor_demo_item( 'سیب‌زمینی ساده', 'نمک دریایی', 55000, 'sides' ),
				flavor_demo_item( 'سیب پنیری', 'چدار آب‌شده', 75000, 'sides' ),
				flavor_demo_item( 'پیاز سوخاری', 'حلقه‌ای', 60000, 'sides' ),
				flavor_demo_item( 'سالاد کلم', 'سس خانگی', 45000, 'sides' ),
				flavor_demo_item( 'هات‌داگ پنیری', 'نان نرم', 115000, 'burger' ),
				flavor_demo_item( 'پیتزا پپرونی شخصی', 'خمیر نازک', 165000, 'burger' ),
				flavor_demo_item( 'پیتزا مرغ و قارچ', 'شخصی', 170000, 'chicken' ),
				flavor_demo_item( 'کمبو خانواده', 'دو برگر + دو سیب + نوشابه', 520000, 'burger' ),
				flavor_demo_item( 'کولا قوطی', '۳۳۰ میلی', 25000, 'drinks' ),
				flavor_demo_item( 'لیموناد خانگی', 'نعنا و لیمو', 45000, 'drinks' ),
				flavor_demo_item( 'شیک شکلات', 'بستنی وانیل', 85000, 'drinks' ),
				flavor_demo_item( 'آب معدنی', '۵۰۰ میلی', 15000, 'drinks' ),
				flavor_demo_item( 'سس سیر اضافه', '۷۰ گرم', 15000, 'sides' ),
				flavor_demo_item( 'چیز فرایز باربیکیو', 'گوشت خردشده', 110000, 'sides' ),
			),
		),
		'traditional'   => array(
			'slug'         => 'traditional',
			'title'        => 'رستوران سنتی',
			'site_title'   => 'سفره خانه نقش‌جهان',
			'tagline'      => 'طعم خانه، ظرف مس',
			'hero_title'   => 'چلوکباب و نان سنگک تازه',
			'hero_text'    => 'دیزی سنگی، خورشت‌های آرام‌پز و چای زغالی در فضای ایرانی.',
			'about'        => 'نقش‌جهان از سال ۱۳۷۵ با دستورهای خانوادگی اصفهان کار می‌کند. برنج طارم و گوشت روزانه.',
			'branch_name'  => 'شعبه نقش جهان',
			'city'         => 'اصفهان',
			'phone'        => '03132221100',
			'address'      => 'خیابان استانداری',
			'categories'   => array( 'کباب' => 'kebab', 'خورشت' => 'stew', 'پیش‌غذا' => 'start', 'نوشیدنی' => 'drinks' ),
			'testimonials' => array(
				array( 'name' => 'حسن علوی', 'text' => 'دیزی‌شان یاد سفره‌های قدیم است.' ),
				array( 'name' => 'مریم شفیعی', 'text' => 'برای مهمان خارجی بهترین معرفی ایران بود.' ),
			),
			'items'        => array(
				flavor_demo_item( 'چلو کباب کوبیده', 'دو سیخ، گوجه کبابی', 280000, 'kebab', array( 'modifiers' => array( array( 'type' => 'cook', 'name' => 'آبدار', 'price' => 0, 'is_default' => 1 ), array( 'type' => 'cook', 'name' => 'کاملاً پخته', 'price' => 0 ) ) ) ),
				flavor_demo_item( 'چلو Barg', 'برگ گوسفندی', 420000, 'kebab' ),
				flavor_demo_item( 'جوجه کباب زعفرانی', 'ران یا سینه', 310000, 'kebab' ),
				flavor_demo_item( 'کباب بختیاری', 'ترکیب برگ و جوجه', 390000, 'kebab' ),
				flavor_demo_item( 'چلو گوشت', 'ران گوسفند', 350000, 'stew' ),
				flavor_demo_item( 'قورمه سبزی', 'گوشت گوسفند', 245000, 'stew' ),
				flavor_demo_item( 'قیمه نثار', 'خلال و زرشک', 265000, 'stew' ),
				flavor_demo_item( 'فسنجان', 'رب انار ملس', 275000, 'stew' ),
				flavor_demo_item( 'دیزی سنگی', 'نخود و گوشت', 230000, 'stew' ),
				flavor_demo_item( 'باقالی پلو با ماهیچه', 'شوید تازه', 360000, 'stew' ),
				flavor_demo_item( 'زرشک پلو با مرغ', 'ران زعفرانی', 220000, 'stew' ),
				flavor_demo_item( 'کاشک بادمجان', 'نعنا داغ', 95000, 'start' ),
				flavor_demo_item( 'میرزاقاسمی', 'سیر شمال', 90000, 'start' ),
				flavor_demo_item( 'زیتون پرورده', 'انار و گردو', 75000, 'start' ),
				flavor_demo_item( 'بورانی اسفناج', 'ماست چکیده', 70000, 'start', array( 'dietary' => array( 'vegetarian' ) ) ),
				flavor_demo_item( 'نان سنگک تازه', 'کنجد', 25000, 'start' ),
				flavor_demo_item( 'دوغ محلی', 'گل‌محمدی', 35000, 'drinks' ),
				flavor_demo_item( 'شربت خاکشیر', 'تخم شربتی', 40000, 'drinks' ),
				flavor_demo_item( 'چای زغالی', 'قوری برنجی', 30000, 'drinks' ),
				flavor_demo_item( 'فالوده شیرازی', 'آب‌لیمو و گلاب', 65000, 'start' ),
				flavor_demo_item( 'بستنی سنتی', 'زعفران و پسته', 70000, 'start' ),
				flavor_demo_item( 'سالاد شیرازی', 'خیار و گوجه ریز', 45000, 'start', array( 'dietary' => array( 'vegan' ) ) ),
			),
		),
		'fine-dining'   => array(
			'slug'         => 'fine-dining',
			'title'        => 'رستوران لوکس',
			'site_title'   => 'رستوران ژوان',
			'tagline'      => 'منوی چشایی، pairing نوشیدنی',
			'hero_title'   => 'شش وعده، یک روایت',
			'hero_text'    => 'آشپزخانه باز، مواد فصل و pairing نوشیدنی‌های بدون الکل.',
			'about'        => 'ژوان منوی چشایی فصلی ارائه می‌دهد. رزرو از ۴۸ ساعت قبل توصیه می‌شود.',
			'branch_name'  => 'شعبه فرشته',
			'city'         => 'تهران',
			'phone'        => '02122660077',
			'address'      => 'فرشته، خیابان فیاضی',
			'categories'   => array( 'چشایی' => 'tasting', 'پیش‌غذا' => 'starter', 'اصلی' => 'main', 'نوشیدنی' => 'drinks' ),
			'testimonials' => array(
				array( 'name' => 'لیلا افشار', 'text' => 'سرویس بی‌نقص و ریتم غذاها دقیق بود.' ),
				array( 'name' => 'بهروز نادری', 'text' => 'pairing نوشیدنی‌ها هوشمندانه طراحی شده.' ),
			),
			'items'        => array(
				flavor_demo_item( 'منوی چشایی شش وعده', 'بدون نوشیدنی', 1850000, 'tasting' ),
				flavor_demo_item( 'منوی چشایی با pairing', 'شش نوشیدنی', 2450000, 'tasting' ),
				flavor_demo_item( 'آمیوز بوش فصل', 'لقمه سرآشپز', 180000, 'starter' ),
				flavor_demo_item( 'تارتار ماهی سفید', 'مرکبات شمال', 320000, 'starter' ),
				flavor_demo_item( 'سوپ کدو حلوایی', 'روغن فندق', 210000, 'starter', array( 'dietary' => array( 'vegetarian' ) ) ),
				flavor_demo_item( 'ریزوتو زعفران', 'کره قهوه‌ای', 390000, 'main', array( 'dietary' => array( 'vegetarian' ) ) ),
				flavor_demo_item( 'فیله گوساله', 'سس شراب بی‌الکل انار', 620000, 'main', array( 'modifiers' => array( array( 'type' => 'cook', 'name' => 'مدیوم ریر', 'price' => 0, 'is_default' => 1 ), array( 'type' => 'cook', 'name' => 'مدیوم', 'price' => 0 ) ) ) ),
				flavor_demo_item( 'ماهی شوریده', 'کره لیمو و کپر', 540000, 'main' ),
				flavor_demo_item( 'مرغ پخته آهسته', 'پوره کرفس', 410000, 'main' ),
				flavor_demo_item( 'پیش‌غذا سبزیجات فصل', 'خاکستر تره', 260000, 'starter', array( 'dietary' => array( 'vegan' ) ) ),
				flavor_demo_item( 'پنیرهای ایرانی', 'عسل گون و گردو', 280000, 'starter' ),
				flavor_demo_item( 'دسر شکلات تلخ', '۷۲ درصد', 190000, 'starter' ),
				flavor_demo_item( 'سوربت زرشک', ' palet cleanser', 120000, 'starter' ),
				flavor_demo_item( 'نان خمیرترش', 'کره نمک‌سود', 65000, 'starter' ),
				flavor_demo_item( 'آب گازدار خانه', 'بطری', 45000, 'drinks' ),
				flavor_demo_item( 'pairing بدون الکل', 'شش گیلاس', 620000, 'drinks' ),
				flavor_demo_item( 'چای سفید', 'دم‌آوری میزی', 85000, 'drinks' ),
				flavor_demo_item( 'قهوه فیلتر', 'تک‌خاستگاه', 95000, 'drinks' ),
				flavor_demo_item( 'اسموثی خیار و بادرنجبویه', 'پیش از غذا', 90000, 'drinks' ),
				flavor_demo_item( 'حلوا هویج مدرن', 'بستنی ماست', 175000, 'starter' ),
				flavor_demo_item( 'سالاد برگ‌های تلخ', 'vinaigrette انار', 210000, 'starter' ),
				flavor_demo_item( 'سوپ سرد ماست', 'خیار و شوید', 160000, 'starter' ),
			),
		),
		'pastry'        => array(
			'slug'         => 'pastry',
			'title'        => 'شیرینی‌فروشی',
			'site_title'   => 'شیرینی‌خانه وانیل',
			'tagline'      => 'کیک سفارشی و شیرینی فرانسوی',
			'hero_title'   => 'کیک عروسی، شیرینی عصر',
			'hero_text'    => 'ماکارون، تارت فصل و پیش‌سفارش کیک تولد از ۴۸ ساعت قبل.',
			'about'        => 'وانیلا با کره حیوانی و شکلات بلژیکی کار می‌کند. سفارش کیک از فرم رویداد.',
			'branch_name'  => 'شعبه زعفرانیه',
			'city'         => 'تهران',
			'phone'        => '02122445566',
			'address'      => 'زعفرانیه، مقدس اردبیلی',
			'categories'   => array( 'کیک' => 'cake', 'شیرینی' => 'sweet', 'صبحانه شیرین' => 'brunch', 'نوشیدنی' => 'drinks' ),
			'testimonials' => array(
				array( 'name' => 'هستی مرادی', 'text' => 'کیک نامزدی دقیقاً مطابق اسکچ بود.' ),
				array( 'name' => 'پارسا کریمی', 'text' => 'کروسان‌شان لایه‌لایه و کره‌ای است.' ),
			),
			'items'        => array(
				flavor_demo_item( 'اسلایس کیک وانیل', 'خامه فرانسوی', 95000, 'cake' ),
				flavor_demo_item( 'ردولوت', 'پنیر خامه‌ای', 105000, 'cake' ),
				flavor_demo_item( 'کیک شکلاتی مرطوب', 'گاناش', 110000, 'cake' ),
				flavor_demo_item( 'چیزکیک توت', 'بیسکویت کره‌ای', 98000, 'cake' ),
				flavor_demo_item( 'ماکارون ۶ تایی', 'طعم مخلوط', 120000, 'sweet' ),
				flavor_demo_item( 'اکلر قهوه', 'کرم پاتیسیر', 65000, 'sweet' ),
				flavor_demo_item( 'تارت لیمو', 'مرنگ ایتالیایی', 75000, 'sweet' ),
				flavor_demo_item( 'تارت میوه فصل', 'کرم بادام', 80000, 'sweet' ),
				flavor_demo_item( 'کروسان ساده', 'کره AOP', 48000, 'brunch' ),
				flavor_demo_item( 'کروسان بادام', 'فرانگipan', 62000, 'brunch' ),
				flavor_demo_item( 'پین ویل دارچین', 'یخ‌شکر', 55000, 'brunch' ),
				flavor_demo_item( 'موفین بلوبری', 'آرد کامل', 45000, 'brunch' ),
				flavor_demo_item( 'کوکی نمک دریا', 'شکلات ۶۶', 38000, 'sweet' ),
				flavor_demo_item( 'براونی فاج', 'گردوی تویسرکان', 52000, 'sweet' ),
				flavor_demo_item( 'نان شیرمال زعفرانی', 'صبح', 40000, 'brunch', array( 'schedule' => array( 'breakfast' ) ) ),
				flavor_demo_item( 'لاته وانیل', 'شربت خانگی', 78000, 'drinks' ),
				flavor_demo_item( 'چای لاته', 'ماسالا ملایم', 70000, 'drinks' ),
				flavor_demo_item( 'هات‌چاکلت سفید', 'گل‌سرخ', 72000, 'drinks' ),
				flavor_demo_item( 'کیک تولد ۱.۵ کیلو', 'پیش‌سفارش', 1850000, 'cake' ),
				flavor_demo_item( 'کیک عروسی از', 'شروع قیمت هر کیلو', 950000, 'cake' ),
				flavor_demo_item( 'باکس هدیه ۱۲ تکه', 'مخلوط', 420000, 'sweet' ),
				flavor_demo_item( 'شیرینی نخودچی ۵۰۰گ', 'نوروز', 185000, 'sweet' ),
			),
		),
		'juice-bar'     => array(
			'slug'         => 'juice-bar',
			'title'        => 'آبمیوه و اسموتی',
			'site_title'   => 'بار سبز',
			'tagline'      => 'پرس سرد، بدون شکر افزوده',
			'hero_title'   => 'سبز، نارنجی، تازه امروز',
			'hero_text'    => 'اسموتی پروتئین، شات زنجبیل و آبمیوه‌های فصل شمال.',
			'about'        => 'بار سبز مواد را هر صبح از میدان تره‌بار می‌آورد. ارزش کالری روی کارت هر آیتم است.',
			'branch_name'  => 'شعبه اندرزگو',
			'city'         => 'تهران',
			'phone'        => '02122667788',
			'address'      => 'اندرزگو، قیطریه',
			'categories'   => array( 'آبمیوه' => 'juice', 'اسموتی' => 'smoothie', 'شات سلامت' => 'shot', 'کاسه' => 'bowl' ),
			'testimonials' => array(
				array( 'name' => 'نیلوفر احمدی', 'text' => 'اسموتی اسفناج طعم علف نمی‌دهد؛ عالی است.' ),
				array( 'name' => 'رضا کمالی', 'text' => 'بعد از باشگاه شات زنجبیل‌شان عادت شده.' ),
			),
			'items'        => array(
				flavor_demo_item( 'پرتقال تازه', '۳۰۰ میلی', 65000, 'juice', array( 'extra' => array( 'calories' => 140 ) ) ),
				flavor_demo_item( 'آب هویج', 'زنجبیل اختیاری', 60000, 'juice' ),
				flavor_demo_item( 'سبز سم‌زدا', 'کرفس، سیب، خیار', 85000, 'juice', array( 'dietary' => array( 'vegan' ) ) ),
				flavor_demo_item( 'انار فصل', 'فقط پاییز و زمستان', 90000, 'juice' ),
				flavor_demo_item( 'لیموناد زنجبیل', 'عسل گز', 55000, 'juice' ),
				flavor_demo_item( 'آب هندوانه', 'نعنا', 58000, 'juice' ),
				flavor_demo_item( 'اسموتی توت و موز', 'شیر بادام', 95000, 'smoothie', array( 'dietary' => array( 'vegan' ) ) ),
				flavor_demo_item( 'اسموتی انبه', 'نارگیل', 98000, 'smoothie' ),
				flavor_demo_item( 'پروتئین بادام‌زمینی', 'وزنه ۳۰ گرم', 120000, 'smoothie' ),
				flavor_demo_item( 'اسموتی اسفناج', 'آناناس و لیمو', 92000, 'smoothie' ),
				flavor_demo_item( 'شات زنجبیل', '۳۰ میلی', 35000, 'shot' ),
				flavor_demo_item( 'شات زردچوبه', 'فلفل سیاه', 35000, 'shot' ),
				flavor_demo_item( 'شات جوانه گندم', 'عسل', 40000, 'shot' ),
				flavor_demo_item( 'آسیایی آکای', 'گرانولا', 145000, 'bowl' ),
				flavor_demo_item( 'کاسه ماست یونانی', 'عسل و گردو', 125000, 'bowl' ),
				flavor_demo_item( 'اوتمیل شبانه', 'چیای و توت', 110000, 'bowl', array( 'schedule' => array( 'breakfast' ) ) ),
				flavor_demo_item( 'آب نارگیل', 'جعبه', 70000, 'juice' ),
				flavor_demo_item( 'ماچا لاته گیاهی', 'شیر جو دوسر', 88000, 'smoothie' ),
				flavor_demo_item( 'آیس تی سبز', 'لیمو', 45000, 'juice' ),
				flavor_demo_item( 'سالاد میوه', 'فصل', 115000, 'bowl' ),
				flavor_demo_item( 'آب سیب سبز', 'پرس سرد', 62000, 'juice' ),
				flavor_demo_item( 'ترکیب ایمنی', 'پرتقال، هویج، زنجبیل', 80000, 'juice' ),
			),
		),
		'catering'      => array(
			'slug'         => 'catering',
			'title'        => 'کترینگ',
			'site_title'   => 'کترینگ رویداد پارس',
			'tagline'      => 'همایش، عروسی، شرکتی',
			'hero_title'   => 'منوی نفرشمار، اجرای بی‌حاشیه',
			'hero_text'    => 'پکیج صبحانه کاری تا شام رسمی. تاریخ و تعداد مهمان را انتخاب کنید.',
			'about'        => 'پارس از ۱۳۸۸ خدمات کترینگ سازمانی ارائه می‌دهد. تیم اجرا و ظروف کرایه جداگانه قابل سفارش است.',
			'branch_name'  => 'آشپزخانه مرکزی جاده مخصوص',
			'city'         => 'تهران',
			'phone'        => '02144990011',
			'address'      => 'جاده مخصوص، شهرک صنعتی',
			'categories'   => array( 'پکیج نفرشمار' => 'pack', 'فینگر فود' => 'finger', 'نوشیدنی سازمانی' => 'bev', 'اضافات' => 'extra' ),
			'testimonials' => array(
				array( 'name' => 'روابط عمومی بانک ملت', 'text' => 'همایش ۴۰۰ نفره بدون تأخیر سرو شد.' ),
				array( 'name' => 'آژانس رویداد آفتاب', 'text' => 'منوی وگان جداگانه عالی مدیریت شد.' ),
			),
			'items'        => array(
				flavor_demo_item( 'پکیج ناهار اقتصادی', 'خوراک + سالاد + نوشیدنی، هر نفر', 185000, 'pack' ),
				flavor_demo_item( 'پکیج ناهار رسمی', 'دو خوراک + دسر', 275000, 'pack' ),
				flavor_demo_item( 'پکیج شام عروسی', 'شش آیتم گرم', 420000, 'pack' ),
				flavor_demo_item( 'صبحانه کاری', 'نان، پنیر، املت، چای', 145000, 'pack', array( 'schedule' => array( 'breakfast' ) ) ),
				flavor_demo_item( 'کافه‌بریک', 'شیرینی + قهوه + چای', 85000, 'pack' ),
				flavor_demo_item( 'فینگر فود ۳۰ تکه', 'سینی مختلط', 320000, 'finger' ),
				flavor_demo_item( 'فینگر فود ۶۰ تکه', 'سینی بزرگ', 590000, 'finger' ),
				flavor_demo_item( 'کاناپه سالمون', '۲۰ عدد', 280000, 'finger' ),
				flavor_demo_item( 'مینی برگر', '۲۰ عدد', 260000, 'finger' ),
				flavor_demo_item( 'اسپرینگ رول سبزیجات', '۲۰ عدد', 190000, 'finger', array( 'dietary' => array( 'vegan' ) ) ),
				flavor_demo_item( 'سینی پنیر و انگور', '۱۰ نفر', 340000, 'finger' ),
				flavor_demo_item( ' intra آبمیوه', 'دیسپنسر ۵ لیتر', 210000, 'bev' ),
				flavor_demo_item( ' intra شربت', '۵ لیتر', 160000, 'bev' ),
				flavor_demo_item( 'ایستگاه قهوه', '۲ ساعت، اپراتور', 890000, 'bev' ),
				flavor_demo_item( 'ظروف یک‌بار لوکس', 'هر نفر', 18000, 'extra' ),
				flavor_demo_item( 'گارسون اضافه', 'هر نفرساعت', 120000, 'extra' ),
				flavor_demo_item( 'کیک همایش', 'لوگوی خوراکی', 1500000, 'extra' ),
				flavor_demo_item( 'منوی کودک', 'هر نفر', 125000, 'pack' ),
				flavor_demo_item( 'منوی وگان', 'هر نفر', 195000, 'pack', array( 'dietary' => array( 'vegan' ) ) ),
				flavor_demo_item( 'دسر لیوانی', '۲۰ عدد', 220000, 'finger' ),
				flavor_demo_item( 'سوپ فصل', 'دیگ ۲۰ نفر', 380000, 'pack' ),
				flavor_demo_item( 'چلوکباب صنعتی', 'هر نفر', 245000, 'pack' ),
			),
		),
		'cloud-kitchen' => array(
			'slug'         => 'cloud-kitchen',
			'title'        => 'آشپزخانه ابری',
			'site_title'   => 'کیتچن‌هاب',
			'tagline'      => 'چند برند، یک آشپزخانه',
			'hero_title'   => 'فقط ارسال. سریع‌ترین مسیر تا در خانه',
			'hero_text'    => 'برگر، سوشی و پاستا از یک سقف. بدون سالن، بدون انتظار میز.',
			'about'        => 'کیتچن‌هاب سه برند مجازی را از یک آشپزخانه ابری در تهرانپارس بیرون می‌دهد.',
			'branch_name'  => 'هاب تهرانپارس',
			'city'         => 'تهران',
			'phone'        => '02177771212',
			'address'      => 'تهرانپارس، خیابان رشید',
			'categories'   => array( 'برند برگر' => 'b1', 'برند سوشی' => 'b2', 'برند پاستا' => 'b3', 'اضافه' => 'extra' ),
			'testimonials' => array(
				array( 'name' => 'مهدی جعفری', 'text' => '۲۵ دقیقه درب منزل؛ بسته‌بندی تمیز.' ),
				array( 'name' => 'آتنا رستمی', 'text' => 'سوشی‌شان برای کلودکیتچن غیرمنتظره تازه بود.' ),
			),
			'items'        => array(
				flavor_demo_item( 'برگر هاب', '۱۸۰ گرم', 195000, 'b1' ),
				flavor_demo_item( 'برگر تند', 'سس هابانرو', 205000, 'b1', array( 'dietary' => array( 'spicy' ) ) ),
				flavor_demo_item( 'سیب هاب', 'ادویه دودی', 60000, 'b1' ),
				flavor_demo_item( 'چیکن رپ', 'نان تورتیلا', 155000, 'b1' ),
				flavor_demo_item( 'سوشی سالمون ۸ تکه', 'نوری', 240000, 'b2' ),
				flavor_demo_item( 'کالیفرنیا رول', '۸ تکه', 185000, 'b2' ),
				flavor_demo_item( 'ساشیمی ترکیبی', '۱۲ تکه', 320000, 'b2' ),
				flavor_demo_item( 'ادامامه', 'نمک دریا', 65000, 'b2', array( 'dietary' => array( 'vegan' ) ) ),
				flavor_demo_item( 'میسو سوپ', 'توفا', 55000, 'b2' ),
				flavor_demo_item( 'پاستا آلفردو', 'مرغ', 210000, 'b3' ),
				flavor_demo_item( 'اسپاگتی بلونز', 'گوشت چرخ‌کرده', 195000, 'b3' ),
				flavor_demo_item( 'پنه آرابیتا', 'تند', 175000, 'b3', array( 'dietary' => array( 'vegetarian', 'spicy' ) ) ),
				flavor_demo_item( 'فتوچینی قارچ', 'خامه', 185000, 'b3', array( 'dietary' => array( 'vegetarian' ) ) ),
				flavor_demo_item( 'سالاد سزار ارسال', 'بسته‌بندی جدا', 125000, 'extra' ),
				flavor_demo_item( 'نوشابه خانواده', '۱.۵ لیتر', 45000, 'extra' ),
				flavor_demo_item( 'سس اضافه', 'انتخابی', 15000, 'extra' ),
				flavor_demo_item( 'چاپستیک و دستمال', 'ست', 5000, 'extra' ),
				flavor_demo_item( 'کمبو سوشی + میسو', 'صرفه‌جویی', 275000, 'b2' ),
				flavor_demo_item( 'کمبو برگر + سیب + نوشابه', 'هاب باکس', 265000, 'b1' ),
				flavor_demo_item( 'تیرامیسو لیوانی', 'دسر سرد', 85000, 'b3' ),
				flavor_demo_item( 'رامن مرغ', 'آبگوشت ۱۶ ساعته', 230000, 'b2' ),
				flavor_demo_item( 'کوکی جعبه ۴ تایی', 'همراه سفارش', 60000, 'extra' ),
			),
		),
	);
}
