/* Real cookie verification and protected customer/order data; SMS request intercepted. */
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import AxeBuilder from '@axe-core/playwright';
export async function testCustomer(page,context,report,base,output){
 const fixture=JSON.parse(await fs.readFile(process.env.QA_FIXTURES_FILE||path.resolve('../../.cache/ui-qa/fixtures.json'),'utf8'));
 async function audit(label){const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.accessibility.push({label,violations:result.violations});assert.equal(result.violations.length,0,label+': '+result.violations.map(v=>v.id).join(', '));}
 await context.clearCookies();
 await page.goto(new URL('my-account/',base).href,{waitUntil:'networkidle'});
 await page.waitForSelector('[data-flavor-auth]:not([hidden])');
 await page.setViewportSize({width:1440,height:1000});
 await audit('phone-login-desktop');
 await page.screenshot({path:path.join(output,'login-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await audit('phone-login-mobile');
 let sends=0;
 await page.route('**/wp-json/flavor/v1/auth/otp/request',async route=>{sends++;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,data:{ok:true,mobile:fixture.mobile,ttl:2,dev:false},meta:{},errors:[]})});});
 await page.locator('#flavor-account-mobile').fill('123');
 await page.locator('[data-auth-send]').click();
 assert.equal(sends,0,'Invalid number triggered a send.');
 await page.locator('#flavor-account-mobile').fill(fixture.mobile);
 await page.locator('[data-auth-send]').click();
 await page.waitForSelector('[data-auth-code-box]:not([hidden])');
 assert.equal(sends,1);
 await page.locator('#flavor-account-code').fill('99999');
 await page.locator('[data-auth-verify]').click();
 await page.waitForSelector('[data-auth-status][data-error="yes"]');
 assert.equal(await page.locator('[data-auth-code-box]').isVisible(),true);
 await page.locator('#flavor-account-code').fill(fixture.code);
 await Promise.all([page.waitForURL('**/my-account/'),page.locator('[data-auth-verify]').click()]);
 await page.waitForSelector('.flavor-account-dashboard',{timeout:20000});
 await page.unroute('**/wp-json/flavor/v1/auth/otp/request');
 assert.ok((await context.cookies()).some(cookie=>cookie.name.startsWith('wordpress_logged_in')&&cookie.httpOnly),'Expected an HttpOnly WP login cookie.');
 assert.equal(await page.evaluate(()=>Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)).some(key=>/token|auth|password/i.test(key))),false,'Theme persisted login credentials.');
 await page.setViewportSize({width:1440,height:1000});
 await audit('customer-dashboard-desktop');
 await page.screenshot({path:path.join(output,'account-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await audit('customer-dashboard-mobile');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.goto(new URL('my-account/orders/',base).href,{waitUntil:'networkidle'});
 assert.ok((await page.locator('.woocommerce-orders-table').textContent()).includes(String(fixture.orders[0])));
 assert.ok(!(await page.locator('.woocommerce-orders-table').textContent()).includes('#'+String(fixture.orders[1])));
 await page.goto(new URL('my-account/view-order/'+fixture.orders[0]+'/',base).href,{waitUntil:'networkidle'});
 assert.equal(await page.locator('.flavor-order-receipt').count(),1);
 assert.equal(await page.locator('.flavor-order-timeline').count(),0,'Unpaid/no-ticket order claimed preparation.');
 await audit('owned-order-receipt');
 await page.goto(new URL('my-account/view-order/'+fixture.orders[1]+'/',base).href,{waitUntil:'networkidle'});
 assert.equal(await page.locator('.flavor-order-receipt').count(),0,'Foreign customer order displayed.');
 await page.goto(new URL('tracking/',base).href,{waitUntil:'networkidle'});
 await page.waitForSelector('[data-ui-tracking]:not([hidden])');
 await page.locator('#flavor-track-id').fill(String(fixture.orders[2]));
 await page.locator('#flavor-track-token').fill(fixture.guest_token);
 await page.locator('[data-ui-tracking] [type="submit"]').click();
 await page.waitForSelector('[data-ui-track-result]:not([hidden])');
 assert.equal((await page.locator('.flavor-order-timeline [aria-current="step"] strong').textContent()).trim(),'آمادهٔ تحویل یا سرو');
 assert.ok(!page.url().includes(fixture.guest_token));
 await audit('verified-guest-order');
 await page.screenshot({path:path.join(output,'tracking-mobile.png'),fullPage:true});
 await page.locator('#flavor-track-token').fill('0'.repeat(64));
 await page.locator('[data-ui-tracking] [type="submit"]').click();
 await page.waitForSelector('[data-ui-track-error]:not([hidden])');
 assert.equal(await page.locator('[data-ui-track-result]').isVisible(),false,'Denied token left old private details displayed.');
 report.checks.push('OTP send intercepted / invalid mobile never sent / real seeded verification and HttpOnly cookie','real customer dashboard and native order history','no persisted auth credentials','native foreign-order denial','unpaid/no-ticket receipt has no invented kitchen progress','real guest-token access and rejected-token clearing / no URL secret');
 await context.clearCookies();
}
