<?php
/** Real delivery-zone data and non-mutating eligibility check. @package Flavor */
defined( 'ABSPATH' ) || exit;
$zones = class_exists( \FlavorCore\Delivery\ZoneRepository::class ) ? \FlavorCore\Delivery\ZoneRepository::for_branch( \Flavor\Enqueue::current_branch_id(), true ) : array();
$hoods = array();
foreach ( $zones as $zone ) { $hoods = array_merge( $hoods, $zone['neighborhoods'] ?? array() ); }
$hoods = array_unique( $hoods );
$demo = \Flavor\Bespoke_Demos::demo();
?>
<section class="fd-section fd-coverage" id="coverage" aria-labelledby="fd-coverage-title"><div class="flavor-container fd-coverage__grid"><div><span class="fd-eyebrow"><?php echo esc_html( \Flavor\Bespoke_Demos::value( 'coverage_eyebrow' ) ); ?></span><h2 id="fd-coverage-title"><?php echo esc_html( \Flavor\Bespoke_Demos::value( 'coverage_title' ) ); ?></h2><p class="fd-prose"><?php echo esc_html( \Flavor\Bespoke_Demos::value( 'coverage_text' ) ); ?></p><a class="fd-text-link" href="<?php echo esc_url( \Flavor\Bespoke_Demos::page_url( 'menu' ) ); ?>"><?php esc_html_e( 'انتخاب غذا و روش دریافت', 'flavor' ); ?><?php \Flavor\Bespoke_Demos::icon( 'arrow', 19 ); ?></a></div><div class="fd-coverage__card">
<?php if ( $zones ) : ?>
	<div class="fd-coverage__zones"><?php foreach ( $zones as $zone ) : ?><div><h3><?php echo esc_html( $zone['name'] ); ?></h3><?php if ( $zone['neighborhoods'] ) : ?><ul class="fd-coverage__hoods"><?php foreach ( $zone['neighborhoods'] as $hood ) : ?><li><?php echo esc_html( $hood ); ?></li><?php endforeach; ?></ul><?php endif; ?><dl><div><dt><?php esc_html_e( 'هزینهٔ ارسال', 'flavor' ); ?></dt><dd><?php echo esc_html( \FlavorCore\WooCommerce\Currency::format( (int) $zone['delivery_fee'] ) ); ?></dd></div><div><dt><?php esc_html_e( 'حداقل سفارش', 'flavor' ); ?></dt><dd><?php echo esc_html( \FlavorCore\WooCommerce\Currency::format( (int) $zone['min_order'] ) ); ?></dd></div></dl></div><?php endforeach; ?></div>
<?php else : ?><p><?php esc_html_e( 'منطقهٔ ارسال فعالی تنظیم نشده است. برای هماهنگی دریافت بیرون‌بر با ما تماس بگیر.', 'flavor' ); ?></p><?php endif; ?>
	<form data-fd-coverage hidden><label for="fd-coverage-hood"><?php esc_html_e( 'نام محله', 'flavor' ); ?></label><div class="fd-coverage__form-row"><input id="fd-coverage-hood" name="neighborhood" type="text" list="fd-coverage-list" placeholder="<?php esc_attr_e( 'مثلاً ونک', 'flavor' ); ?>" autocomplete="address-level3" required maxlength="100" /><button class="fd-button fd-button--primary" type="submit"><?php esc_html_e( 'بررسی محله', 'flavor' ); ?></button></div><datalist id="fd-coverage-list"><?php foreach ( $hoods as $hood ) : ?><option value="<?php echo esc_attr( $hood ); ?>"></option><?php endforeach; ?></datalist><input type="hidden" name="city" value="<?php echo esc_attr( $demo['city'] ); ?>" /><p class="fd-coverage__result" data-fd-coverage-result role="status" aria-live="polite"></p></form><noscript><p><?php esc_html_e( 'بررسی آنلاین محله به JavaScript نیاز دارد. محدوده‌های بالا از تنظیمات شعبه خوانده شده‌اند؛ برای هماهنگی تماس بگیر.', 'flavor' ); ?></p></noscript>
	<small><?php esc_html_e( 'زمان احتمالی ارسال، برآورد منطقه است؛ نه رهگیری زنده یا زمان تضمین‌شده.', 'flavor' ); ?></small></div></div></section>
