#!/usr/bin/env python3
"""
Flavor Mobile Brand Provisioning Tool.

Applies the CANONICAL white-label branding configuration (see
docs/MOBILE-WHITELABEL-CONTRACT.md) served by the WordPress REST endpoint
``GET /flavor/v1/mobile/config`` — or supplied via a local JSON file — to the
Flutter, Android, and iOS projects during CI/CD.

Contract guarantees implemented here:

* Both the canonical nested schema and the legacy flat schema are accepted,
  but everything is normalized to the canonical nested shape before use.
* Every value is validated BEFORE it is written (package names, URLs, hex
  colors, version names/codes, slugs). Invalid required values abort the
  build with a non-zero exit code.
* Every value is escaped for the target file format (Dart string literals,
  Android XML attributes, plist XML, Groovy/Gradle strings).
* Android: ``applicationId`` is provisioned per brand, but the Gradle
  ``namespace`` and the Kotlin package tree stay FIXED at
  ``com.flavor.restaurant`` (stable-native-package architecture).
* iOS: ``CFBundleDisplayName`` / ``CFBundleURLName`` are provisioned plist-side;
  the bundle identifier is provisioned into ``project.pbxproj`` when it is
  present (it is generated by ``flutter create`` in CI and may be absent
  from the repo).

Usage:
  python3 provision_brand.py --config-url https://site.example/wp-json/flavor/v1/mobile/config
  python3 provision_brand.py --config-file path/to/brand_config.json
"""

import argparse
import json
import os
import re
import sys
import urllib.request
from urllib.parse import urlparse
from xml.sax.saxutils import escape as xml_escape

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CANONICAL_SCHEMA_ID = "flavor-mobile-branding@1"

# The native package is an architectural constant: Gradle `namespace` and the
# Kotlin source tree never move, only `applicationId` varies per brand.
STABLE_NATIVE_PACKAGE = "com.flavor.restaurant"

DEFAULTS = {
    "app_name": "Flavor Restaurant",
    "tenant_id": "default_tenant",
    "api_base_url": "https://demo.flavor.restaurant/wp-json/flavor/v2",
    "default_branch_id": 0,
    "branding": {
        "primary_color": "#C62828",
        "secondary_color": "#2E7D32",
        "accent_color": "#FFA000",
        "font_family": "Vazirmatn",
        "border_radius": 12.0,
    },
    "contact": {
        "phone": "021-88888888",
        "email": "support@flavor.restaurant",
        "website": "",
    },
    "legal": {
        "privacy_policy": "",
        "terms": "",
    },
    "assets": {
        "logo_url": "",
        "icon_url": "",
        "splash_url": "",
    },
    "deep_links": {
        "domains": [],
    },
}

# Android package-name rules: dot-separated segments, each starting with a
# letter, containing letters/digits/underscores. Two segments minimum.
APP_ID_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$")
MAX_APP_ID_LEN = 255

# Semantic version name: MAJOR.MINOR.PATCH with optional pre-release suffix.
VERSION_NAME_RE = re.compile(r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.\-]+)?$")
MAX_VERSION_CODE = 2_100_000_000  # Google Play maximum.

HEX_COLOR_RE = re.compile(r"^#[0-9a-fA-F]{6}$")
TENANT_ID_RE = re.compile(r"^[a-z0-9][a-z0-9_\-]{0,63}$")
FONT_FAMILY_RE = re.compile(r"^[\w\- ]{1,64}$")
URL_RE = re.compile(r"^https?://[^\s\"'<>`\\]+$")
HOST_RE = re.compile(r"^[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?)+\.?$")
CERT_FINGERPRINT_RE = re.compile(r"^([0-9A-Fa-f]{2}:){31}[0-9A-Fa-f]{2}$")
IOS_TEAM_ID_RE = re.compile(r"^[A-Z0-9]{10}$")
MAX_TEXT_LEN = 200


class ProvisioningError(Exception):
    """Raised when a configuration value fails validation or a target file
    cannot be provisioned safely."""


# ---------------------------------------------------------------------------
# Format-specific escaping helpers (defense in depth after validation)
# ---------------------------------------------------------------------------

_CONTROL_CHARS_RE = re.compile(r"[\x00-\x1f\x7f]")


def strip_control_chars(value: str) -> str:
    """Remove control characters (incl. newlines/CR) from a value."""
    return _CONTROL_CHARS_RE.sub("", value)


def escape_dart(value: str) -> str:
    """Escape *value* for embedding inside a single-quoted Dart string literal."""
    value = strip_control_chars(str(value))
    return (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("$", "\\$")
    )


def escape_xml_text(value: str) -> str:
    """Escape *value* for embedding inside XML element text or attribute."""
    value = strip_control_chars(str(value))
    return xml_escape(value, {"\"": "&quot;", "'": "&apos;"})


def escape_gradle_string(value: str) -> str:
    """Escape *value* for embedding inside a double-quoted Groovy string.

    Validated identifiers never need this, but values into Gradle files go
    through here regardless (GString ``$``-interpolation is neutralized).
    """
    value = strip_control_chars(str(value))
    return value.replace("\\", "\\\\").replace('"', '\\"').replace('$', '\\$')


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ProvisioningError(message)


def validate_app_identifier(value: str, field: str = "app_identifier") -> str:
    _require(isinstance(value, str), f"{field}: must be a string")
    _require(bool(value.strip()), f"{field}: must not be empty")
    _require(len(value) <= MAX_APP_ID_LEN, f"{field}: longer than {MAX_APP_ID_LEN} characters")
    _require(
        bool(APP_ID_RE.match(value)),
        f"{field}: '{value}' is not a valid application identifier "
        f"(dot-separated segments, letters/digits/underscores, each starting with a letter)",
    )
    return value


def validate_version_name(value: str) -> str:
    value = str(value)
    _require(
        bool(VERSION_NAME_RE.match(value)),
        f"version_name: '{value}' must be semantic (e.g. '1.4.2' or '2.0.0-beta1')",
    )
    return value


def validate_version_code(value) -> int:
    if isinstance(value, bool) or value is None:
        raise ProvisioningError(f"version_code: '{value}' is not an integer")
    if isinstance(value, float) and not value.is_integer():
        raise ProvisioningError(f"version_code: {value} is not an integer")
    if isinstance(value, str) and not re.fullmatch(r"\d+", value.strip()):
        raise ProvisioningError(f"version_code: '{value}' is not an integer")
    code = int(value)
    _require(1 <= code <= MAX_VERSION_CODE, f"version_code: {code} out of range 1..{MAX_VERSION_CODE}")
    return code


def validate_color(value: str, field: str) -> str:
    _require(isinstance(value, str) and bool(HEX_COLOR_RE.match(value)),
             f"{field}: '{value}' must be a 6-digit hex color like '#1A2B3C'")
    return value.upper()


def validate_url(value: str, field: str, allow_empty: bool = True) -> str:
    if value is None:
        value = ""
    value = str(value)
    if value == "":
        _require(allow_empty, f"{field}: must not be empty")
        return value
    _require(bool(URL_RE.match(value)),
             f"{field}: '{value}' is not a valid http(s) URL without whitespace/quotes")
    parsed = urlparse(value)
    _require(bool(parsed.netloc), f"{field}: '{value}' has no host")
    return value


def validate_tenant_id(value: str) -> str:
    _require(isinstance(value, str) and bool(TENANT_ID_RE.match(value)),
             f"tenant_id: '{value}' must be a lowercase slug [a-z0-9_-] up to 64 characters")
    return value


def validate_text(value: str, field: str, allow_empty: bool = False, max_len: int = MAX_TEXT_LEN) -> str:
    _require(isinstance(value, str), f"{field}: must be a string")
    _require(allow_empty or bool(value.strip()), f"{field}: must not be empty")
    cleaned = strip_control_chars(value)
    _require(len(cleaned) <= max_len, f"{field}: longer than {max_len} characters")
    return cleaned


def validate_branch_id(value) -> int:
    try:
        branch = int(value)
    except (TypeError, ValueError):
        raise ProvisioningError(f"default_branch_id: '{value}' is not an integer")
    _require(branch >= 0, f"default_branch_id: {branch} must be >= 0")
    return branch


def validate_font_family(value: str) -> str:
    _require(isinstance(value, str) and bool(FONT_FAMILY_RE.match(value)),
             f"branding.font_family: '{value}' contains disallowed characters")
    return value


def validate_border_radius(value) -> float:
    try:
        radius = float(value)
    except (TypeError, ValueError):
        raise ProvisioningError(f"branding.border_radius: '{value}' is not numeric")
    _require(0.0 <= radius <= 200.0, f"branding.border_radius: {radius} out of range 0..200")
    return radius


def validate_config(cfg: dict) -> dict:
    """Validate the normalized canonical configuration in place."""
    validate_app_identifier(cfg["app_identifier"])
    cfg["version_name"] = validate_version_name(cfg["version_name"])
    cfg["version_code"] = validate_version_code(cfg["version_code"])
    cfg["app_name"] = validate_text(cfg["app_name"], "app_name", max_len=100)
    cfg["tenant_id"] = validate_tenant_id(cfg["tenant_id"])
    cfg["api_base_url"] = validate_url(cfg["api_base_url"], "api_base_url", allow_empty=False)
    cfg["default_branch_id"] = validate_branch_id(cfg["default_branch_id"])

    b = cfg["branding"]
    b["primary_color"] = validate_color(b["primary_color"], "branding.primary_color")
    b["secondary_color"] = validate_color(b["secondary_color"], "branding.secondary_color")
    b["accent_color"] = validate_color(b["accent_color"], "branding.accent_color")
    b["font_family"] = validate_font_family(b["font_family"])
    b["border_radius"] = validate_border_radius(b["border_radius"])

    c = cfg["contact"]
    c["phone"] = validate_text(c["phone"], "contact.phone", allow_empty=True)
    c["email"] = validate_text(c["email"], "contact.email", allow_empty=True)
    if c["email"]:
        _require("@" in c["email"] and "." in c["email"].rsplit("@", 1)[-1],
                 f"contact.email: '{c['email']}' is not a valid email address")
    c["website"] = validate_url(c["website"], "contact.website")

    cfg["legal"]["privacy_policy"] = validate_url(cfg["legal"]["privacy_policy"], "legal.privacy_policy")
    cfg["legal"]["terms"] = validate_url(cfg["legal"]["terms"], "legal.terms")

    for key in ("logo_url", "icon_url", "splash_url"):
        cfg["assets"][key] = validate_url(cfg["assets"].get(key, ""), f"assets.{key}")

    # Deep link domains: explicit list wins, otherwise derived from api_base_url.
    if "deep_links" not in cfg or not isinstance(cfg["deep_links"], dict):
        cfg["deep_links"] = {"domains": []}
    explicit = cfg["deep_links"].get("domains") or []
    if not isinstance(explicit, list):
        raise ProvisioningError("deep_links.domains: must be a list of hostnames")
    if explicit:
        domains = [validate_host(d, f"deep_links.domains[{i}]") for i, d in enumerate(explicit)]
    else:
        domains = [validate_host(urlparse(cfg["api_base_url"]).netloc, "deep_links.host(derived)")]
    cfg["deep_links"]["domains"] = sorted(set(domains))

    return cfg


def validate_host(value: str, field: str) -> str:
    value = (value or "").strip().lower()
    _require(bool(value) and bool(HOST_RE.match(value)) and ".." not in value and len(value) <= 253,
             f"{field}: '{value}' is not a valid hostname for App Links / Universal Links")
    _require("_" not in value and " " not in value,
             f"{field}: '{value}' contains characters forbidden in link domains")
    _require(value.split(".")[0] != "*",
             f"{field}: wildcard hosts are not allowed here; provision explicit tenant domains")
    return value


# ---------------------------------------------------------------------------
# Normalization: legacy flat keys -> canonical nested schema
# ---------------------------------------------------------------------------

def _migrate(target: dict, section: str, new_key: str, old_key: str, raw: dict, warnings: list) -> None:
    """Backfill a legacy top-level key into the canonical nested position.

    The canonical nested spelling always wins; the legacy flat key is used
    only when the nested section did not supply the value.
    """
    if old_key not in raw:
        return
    section_raw = raw.get(section)
    if isinstance(section_raw, dict) and new_key in section_raw:
        return  # canonical spelling already winning.
    target[section][new_key] = raw[old_key]
    warnings.append(
        f"deprecated key '{old_key}' -> '{section}.{new_key}' "
        f"(migrate to canonical schema {CANONICAL_SCHEMA_ID})"
    )


def normalize_config(raw: dict) -> dict:
    """Reduce any accepted config shape (canonical nested or legacy flat) to
    the canonical nested schema defined in docs/MOBILE-WHITELABEL-CONTRACT.md."""
    if not isinstance(raw, dict):
        raise ProvisioningError("configuration payload must be a JSON object")

    warnings = []

    # Unwrap REST envelope only when it clearly carries the payload, not
    # WordPress meta/lists (the server returns {"data": {...}, "meta": {...}}).
    if "data" in raw and isinstance(raw["data"], dict) and "app_identifier" in raw["data"]:
        raw = raw["data"]

    cfg = json.loads(json.dumps(DEFAULTS))  # deep copy

    # Top-level fields.
    for key in ("app_name", "version_name", "version_code", "api_base_url",
                "tenant_id", "default_branch_id"):
        if key in raw:
            cfg[key] = raw[key]

    # app_identifier has no default: it MUST come from the payload (canonical)
    # or from the legacy alias package_name.
    if "app_identifier" in raw:
        cfg["app_identifier"] = raw["app_identifier"]
    elif "package_name" in raw:
        cfg["app_identifier"] = raw["package_name"]
        warnings.append(
            f"deprecated key 'package_name' -> 'app_identifier' "
            f"(migrate to canonical schema {CANONICAL_SCHEMA_ID})"
        )

    # Legacy restaurant_id was an alias of tenant_id.
    if "tenant_id" not in raw and "restaurant_id" in raw:
        cfg["tenant_id"] = raw["restaurant_id"]
        warnings.append(
            f"deprecated key 'restaurant_id' -> 'tenant_id' "
            f"(migrate to canonical schema {CANONICAL_SCHEMA_ID})"
        )

    # Nested canonical sections override, then legacy flat backfill.
    for section in ("branding", "contact", "legal", "assets", "deep_links"):
        section_raw = raw.get(section)
        if isinstance(section_raw, dict):
            for key, value in section_raw.items():
                if key in cfg[section]:
                    cfg[section][key] = value

    _migrate(cfg, "branding", "primary_color", "primary_color", raw, warnings)
    _migrate(cfg, "branding", "secondary_color", "secondary_color", raw, warnings)
    _migrate(cfg, "branding", "accent_color", "accent_color", raw, warnings)
    _migrate(cfg, "branding", "font_family", "font_family", raw, warnings)
    _migrate(cfg, "branding", "border_radius", "border_radius", raw, warnings)
    _migrate(cfg, "contact", "phone", "support_phone", raw, warnings)
    _migrate(cfg, "contact", "email", "support_email", raw, warnings)
    _migrate(cfg, "contact", "website", "website_url", raw, warnings)
    _migrate(cfg, "legal", "privacy_policy", "privacy_policy_url", raw, warnings)
    _migrate(cfg, "legal", "terms", "terms_url", raw, warnings)
    _migrate(cfg, "assets", "logo_url", "logo_url", raw, warnings)
    _migrate(cfg, "assets", "icon_url", "icon_url", raw, warnings)
    _migrate(cfg, "assets", "splash_url", "splash_url", raw, warnings)

    _require("app_identifier" in cfg and cfg["app_identifier"],
             "missing required field 'app_identifier' (canonical) / 'package_name' (legacy)")

    for warning in warnings:
        print(f"[!] Deprecation warning: {warning}")

    return validate_config(cfg)


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def fetch_config_from_url(url: str, mobile_dir: str = ".") -> dict:
    print(f"[*] Fetching brand config from API: {url}")
    try:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "Flavor-CI-Provisioner/2.0", "Accept": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            if resp.status != 200:
                raise RuntimeError(f"Failed to fetch config, HTTP status: {resp.status}")
            data = json.loads(resp.read().decode("utf-8"))
            return data.get("data") if isinstance(data.get("data"), dict) else data
    except Exception as e:
        print(f"[!] Warning: Could not fetch config from URL ({e}). Checking local fallback.")
        default_file = os.path.join(mobile_dir, "assets", "branding", "default_branding.json")
        if os.path.exists(default_file):
            print(f"[*] Falling back to local template: {default_file}")
            return load_config_from_file(default_file)
        raise


def load_config_from_file(path: str) -> dict:
    print(f"[*] Loading brand config from file: {path}")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Provisioning steps
# ---------------------------------------------------------------------------

def update_pubspec_yaml(mobile_dir: str, cfg: dict):
    pubspec_path = os.path.join(mobile_dir, "pubspec.yaml")
    if not os.path.exists(pubspec_path):
        print(f"[!] pubspec.yaml not found at {pubspec_path}")
        return

    with open(pubspec_path, "r", encoding="utf-8") as f:
        content = f.read()

    # version_name/version_code are validated, so the YAML line is safe.
    version_line = f"version: {cfg['version_name']}+{cfg['version_code']}"
    content, n = re.subn(r"^version:\s*.*$", version_line, content, count=1, flags=re.MULTILINE)
    if n != 1:
        raise ProvisioningError("pubspec.yaml: could not locate a 'version:' line to update")

    with open(pubspec_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[+] Updated pubspec.yaml version: {cfg['version_name']}+{cfg['version_code']}")


def update_android_branding(mobile_dir: str, cfg: dict):
    """Provision Android: ``applicationId`` per brand, ``namespace`` fixed."""
    build_gradle = os.path.join(mobile_dir, "android", "app", "build.gradle")
    app_id = cfg["app_identifier"]  # already validated

    if os.path.exists(build_gradle):
        with open(build_gradle, "r", encoding="utf-8") as f:
            content = f.read()

        # Enforce the stable-native-package architecture: namespace must match
        # the Kotlin source tree (never brand-dependent).
        ns_match = re.search(r'namespace\s+["\']([^"\']+)["\']', content)
        _require(ns_match, "build.gradle: no 'namespace' declaration found")
        _require(
            ns_match.group(1) == STABLE_NATIVE_PACKAGE,
            f"build.gradle: namespace '{ns_match.group(1)}' != expected stable package "
            f"'{STABLE_NATIVE_PACKAGE}'. The Kotlin source tree is not brand-provisioned; "
            f"keep namespace fixed and vary applicationId only.",
        )

        content, n = re.subn(
            r'applicationId\s+["\'][^"\']+["\']',
            f'applicationId "{escape_gradle_string(app_id)}"',
            content,
            count=1,
        )
        _require(n == 1, "build.gradle: could not locate 'applicationId' to update")

        content, n = re.subn(
            r'versionCode\s+flutterVersionCode\.toInteger\(\)|\bversionCode\s+\d+',
            f"versionCode {cfg['version_code']}",
            content,
            count=1,
        )
        _require(n == 1, "build.gradle: could not locate 'versionCode' to update")

        content, n = re.subn(
            r'versionName\s+flutterVersionName|\bversionName\s+["\'][^"\']*["\']',
            f'versionName "{escape_gradle_string(cfg["version_name"])}"',
            content,
            count=1,
        )
        _require(n == 1, "build.gradle: could not locate 'versionName' to update")

        with open(build_gradle, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"[+] Updated Android build.gradle (applicationId: {app_id}, version: "
              f"{cfg['version_name']} ({cfg['version_code']})) | namespace stable: "
              f"{STABLE_NATIVE_PACKAGE}")

        # Sanity: the Kotlin entry point must exist under the stable package path.
        kotlin_path = os.path.join(
            mobile_dir, "android", "app", "src", "main", "kotlin",
            *STABLE_NATIVE_PACKAGE.split("."), "MainActivity.kt",
        )
        _require(
            os.path.exists(kotlin_path),
            f"Kotlin entry point not found at {kotlin_path}; the native source tree must "
            f"stay in package '{STABLE_NATIVE_PACKAGE}'.",
        )

    manifest_path = os.path.join(mobile_dir, "android", "app", "src", "main", "AndroidManifest.xml")
    if os.path.exists(manifest_path):
        with open(manifest_path, "r", encoding="utf-8") as f:
            m_content = f.read()

        label = escape_xml_text(cfg["app_name"])
        m_content, n = re.subn(
            r'android:label="[^"]*"',
            f'android:label="{label}"',
            m_content,
            count=1,
        )
        _require(n == 1, "AndroidManifest.xml: could not locate android:label to update")
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(m_content)
        print(f"[+] Updated Android Manifest app label: {cfg['app_name']}")


def update_ios_branding(mobile_dir: str, cfg: dict):
    app_id = cfg["app_identifier"]  # validated; XML-safe identifier
    app_name = cfg["app_name"]

    # 1) project.pbxproj holds PRODUCT_BUNDLE_IDENTIFIER; it only exists after
    #    `flutter create` runs in CI, so provision it when present.
    pbxproj = os.path.join(mobile_dir, "ios", "Runner.xcodeproj", "project.pbxproj")
    if os.path.exists(pbxproj):
        with open(pbxproj, "r", encoding="utf-8") as f:
            pbx = f.read()
        pbx, n = re.subn(
            r"PRODUCT_BUNDLE_IDENTIFIER\s*=\s*[^;\s]+",
            f"PRODUCT_BUNDLE_IDENTIFIER = {app_id}",
            pbx,
        )
        with open(pbxproj, "w", encoding="utf-8") as f:
            f.write(pbx)
        print(f"[+] Provisioned iOS bundle identifier in project.pbxproj ({n} occurrence(s)): {app_id}")
    else:
        print("[i] ios/Runner.xcodeproj/project.pbxproj not present (generated by flutter "
              "create in CI); bundle identifier will come from CI with --bundle-identifier.")

    # 2) Info.plist: display name + URL name (plists are XML; escape first).
    info_plist = os.path.join(mobile_dir, "ios", "Runner", "Info.plist")
    if os.path.exists(info_plist):
        with open(info_plist, "r", encoding="utf-8") as f:
            plist = f.read()

        plist, n = re.subn(
            r"(<key>CFBundleDisplayName</key>\s*<string>)[^<]*(</string>)",
            lambda m: m.group(1) + escape_xml_text(app_name) + m.group(2),
            plist,
            count=1,
        )
        _require(n == 1, "Info.plist: could not locate CFBundleDisplayName")

        plist, n = re.subn(
            r"(<key>CFBundleURLName</key>\s*<string>)[^<]*(</string>)",
            lambda m: m.group(1) + escape_xml_text(app_id) + m.group(2),
            plist,
            count=1,
        )
        _require(n == 1, "Info.plist: could not locate CFBundleURLName")

        with open(info_plist, "w", encoding="utf-8") as f:
            f.write(plist)
        print(f"[+] Updated iOS Info.plist (display name: '{app_name}', URL name: {app_id})")


# ---------------------------------------------------------------------------
# Deep link provisioning (App Links / Universal Links / well-known assets)
# ---------------------------------------------------------------------------

def update_android_app_links(mobile_dir: str, cfg: dict):
    """Rewrite the autoverify App Links intent-filter with the tenant domains."""
    manifest_path = os.path.join(mobile_dir, "android", "app", "src", "main", "AndroidManifest.xml")
    if not os.path.exists(manifest_path):
        return
    with open(manifest_path, "r", encoding="utf-8") as f:
        content = f.read()

    data_lines = "\n".join(
        f'            <data android:scheme="https" android:host="{domain}" android:pathPrefix="/" />'
        for domain in cfg["deep_links"]["domains"]  # validated hostnames; XML-safe charset
    )
    new_block = (
        '<intent-filter android:autoVerify="true">\n'
        '            <action android:name="android.intent.action.VIEW" />\n'
        '            <category android:name="android.intent.category.DEFAULT" />\n'
        '            <category android:name="android.intent.category.BROWSABLE" />\n'
        f'{data_lines}\n'
        '        </intent-filter>'
    )

    content, n = re.subn(
        r'<intent-filter\s+android:autoVerify="true">.*?</intent-filter>',
        lambda m: new_block,
        content,
        count=1,
        flags=re.DOTALL,
    )
    _require(n == 1, "AndroidManifest.xml: App Links intent-filter (autoVerify) not found")

    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[+] Provisioned Android App Links: {', '.join(cfg['deep_links']['domains'])}")


def update_ios_entitlements(mobile_dir: str, cfg: dict):
    """Rewrite the Associated Domains entries of Runner.entitlements."""
    ent_path = os.path.join(mobile_dir, "ios", "Runner", "Runner.entitlements")
    if not os.path.exists(ent_path):
        print("[i] ios/Runner/Runner.entitlements not present; skipping Associated Domains.")
        return
    with open(ent_path, "r", encoding="utf-8") as f:
        content = f.read()

    entries = "\n".join(
        f'\t\t<string>applinks:{domain}</string>'
        for domain in cfg["deep_links"]["domains"]
    )
    content, n = re.subn(
        r"(<key>com\.apple\.developer\.associated-domains</key>\s*<array>).*?(</array>)",
        lambda m: m.group(1) + "\n" + entries + "\n\t" + m.group(2),
        content,
        count=1,
        flags=re.DOTALL,
    )
    _require(n == 1, "Runner.entitlements: associated-domains array not found")

    with open(ent_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[+] Provisioned iOS Associated Domains: {', '.join(cfg['deep_links']['domains'])}")


def generate_wellknown_deeplink_files(mobile_dir: str, cfg: dict):
    """Render the hosted well-known link files for this brand.

    Asset Links requires the release certificate SHA-256 (env
    FLAVOR_ANDROID_CERT_FINGERPRINT); Universal Links needs the Apple team id
    (env FLAVOR_IOS_TEAM_ID). In CI these are provided as secrets; locally the
    files are rendered with explicit placeholders (never silently valid).
    """
    tpl_dir = os.path.join(mobile_dir, "assets", "deeplinks")
    out_dir = os.path.join(tpl_dir, "generated")
    os.makedirs(out_dir, exist_ok=True)

    # --- Android assetlinks.json (served at https://<domain>/.well-known/assetlinks.json)
    fingerprint = os.environ.get("FLAVOR_ANDROID_CERT_FINGERPRINT", "").strip()
    if fingerprint:
        _require(bool(CERT_FINGERPRINT_RE.match(fingerprint)),
                 f"FLAVOR_ANDROID_CERT_FINGERPRINT: '{fingerprint}' is not a SHA-256 "
                 "certificate fingerprint (32 hex pairs separated by colons)")
    else:
        fingerprint = "REPLACE_WITH_RELEASE_SHA256_FINGERPRINT"
        print("[!] FLAVOR_ANDROID_CERT_FINGERPRINT not set; assetlinks.json carries a placeholder.")

    for tpl_name, out_name in (("assetlinks.template.json", "assetlinks.json"),):
        tpl_path = os.path.join(tpl_dir, tpl_name)
        if os.path.exists(tpl_path):
            with open(tpl_path, encoding="utf-8") as f:
                rendered = f.read()
            rendered = (rendered
                        .replace("{{APPLICATION_ID}}", cfg["app_identifier"])
                        .replace("{{SHA256_CERT_FINGERPRINT}}", fingerprint))
            with open(os.path.join(out_dir, out_name), "w", encoding="utf-8") as f:
                f.write(rendered)
            print(f"[+] Generated {out_name} for {cfg['app_identifier']}")

    # --- iOS apple-app-site-association (served at https://<domain>/.well-known/apple-app-site-association)
    team_id = os.environ.get("FLAVOR_IOS_TEAM_ID", "").strip()
    if team_id:
        _require(bool(IOS_TEAM_ID_RE.match(team_id)),
                 f"FLAVOR_IOS_TEAM_ID: '{team_id}' must be a 10-char uppercase Apple team id")
    else:
        team_id = "000000TEAM"
        print("[!] FLAVOR_IOS_TEAM_ID not set; apple-app-site-association carries a placeholder.")

    tpl_path = os.path.join(tpl_dir, "apple-app-site-association.template.json")
    if os.path.exists(tpl_path):
        with open(tpl_path, encoding="utf-8") as f:
            rendered = f.read()
        rendered = (rendered
                    .replace("{{TEAM_ID}}", team_id)
                    .replace("{{BUNDLE_ID}}", cfg["app_identifier"]))
        with open(os.path.join(out_dir, "apple-app-site-association"), "w", encoding="utf-8") as f:
            f.write(rendered)
        print(f"[+] Generated apple-app-site-association for {team_id}.{cfg['app_identifier']}")


def generate_branding_dart_constants(mobile_dir: str, cfg: dict):
    target_path = os.path.join(mobile_dir, "lib", "core", "constants", "brand_tokens.g.dart")
    os.makedirs(os.path.dirname(target_path), exist_ok=True)

    b, c, l, a = cfg["branding"], cfg["contact"], cfg["legal"], cfg["assets"]

    def color(hex_color: str) -> str:
        # validated ^#RRGGBB$ -> ARGB 0xFFRRGGBB
        return "0xFF" + hex_color.lstrip("#").upper()

    def num(value) -> str:
        s = str(float(value))
        return s[:-2] if s.endswith(".0") else s

    dart_content = f"""// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Flavor Mobile Brand Provisioning Tool ({CANONICAL_SCHEMA_ID})

import 'package:flutter/material.dart';

abstract class BrandTokens {{
  static const String appName = '{escape_dart(cfg["app_name"])}';
  static const String tenantId = '{escape_dart(cfg["tenant_id"])}';
  static const String apiBaseUrl = '{escape_dart(cfg["api_base_url"])}';
  static const int defaultBranchId = {cfg["default_branch_id"]};

  static const Color primaryColor = Color({color(b["primary_color"])});
  static const Color secondaryColor = Color({color(b["secondary_color"])});
  static const Color accentColor = Color({color(b["accent_color"])});
  static const String fontFamily = '{escape_dart(b["font_family"])}';
  static const double borderRadius = {num(b["border_radius"])};

  static const String supportPhone = '{escape_dart(c["phone"])}';
  static const String supportEmail = '{escape_dart(c["email"])}';
  static const String websiteUrl = '{escape_dart(c["website"])}';
  static const String privacyPolicyUrl = '{escape_dart(l["privacy_policy"])}';
  static const String termsUrl = '{escape_dart(l["terms"])}';

  static const String logoUrl = '{escape_dart(a["logo_url"])}';
  static const String iconUrl = '{escape_dart(a["icon_url"])}';
  static const String splashUrl = '{escape_dart(a["splash_url"])}';
}}
"""
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(dart_content)
    print(f"[+] Generated Dart brand tokens at: {target_path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="Flavor Brand Provisioner for Mobile Apps")
    parser.add_argument("--config-url", type=str, help="WordPress REST API endpoint for brand configuration")
    parser.add_argument("--config-file", type=str, help="Local JSON file with branding parameters")
    parser.add_argument("--mobile-root", type=str, default=".", help="Root directory of Flutter project")
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)

    if args.config_url:
        raw = fetch_config_from_url(args.config_url, mobile_dir=args.mobile_root)
    elif args.config_file:
        raw = load_config_from_file(args.config_file)
    else:
        default_file = os.path.join(args.mobile_root, "assets", "branding", "default_branding.json")
        if os.path.exists(default_file):
            raw = load_config_from_file(default_file)
        else:
            print("[!] Error: You must supply --config-url or --config-file.")
            return 1

    try:
        cfg = normalize_config(raw)
        print(f"[*] Applying white-label configuration for tenant: {cfg['tenant_id']}")
        update_pubspec_yaml(args.mobile_root, cfg)
        update_android_branding(args.mobile_root, cfg)
        update_ios_branding(args.mobile_root, cfg)
        update_android_app_links(args.mobile_root, cfg)
        update_ios_entitlements(args.mobile_root, cfg)
        generate_wellknown_deeplink_files(args.mobile_root, cfg)
        generate_branding_dart_constants(args.mobile_root, cfg)
    except ProvisioningError as e:
        print(f"[✗] Provisioning rejected: {e}")
        return 2

    print("[✓] Brand provisioning completed successfully!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
