<?php
/** Real-capacity reservation picker; no dining service is invented. @package Flavor */
defined( 'ABSPATH' ) || exit;
$eligible = array();
if ( \Flavor\Theme_Setup::has_core() ) { foreach ( get_posts( array( 'post_type'=>'flavor_branch','post_status'=>'publish','posts_per_page'=>50,'fields'=>'ids' ) ) as $id ) { if ( \Flavor\UI::reservation_available( (int) $id ) ) { $eligible[] = (int) $id; } } }
?>
<div class="flavor-container flavor-res" id="flavor-res">
 <?php \Flavor\UI_Pages::breadcrumb( __( 'رزرو', 'flavor' ) ); ?>
 <div class="flavor-ui-page-head"><div><span class="flavor-ui-overline"><?php echo esc_html( get_bloginfo( 'name' ) ); ?></span><h1><?php esc_html_e( 'زمانی برای دور هم بودن.', 'flavor' ); ?></h1><p><?php esc_html_e( 'شعبه، تعداد مهمان و زمان را انتخاب کنید. ساعت‌ها از ظرفیت واقعی خوانده می‌شوند؛ تا ارسال فرم و پاسخ موفق سرور، رزروی ثبت نشده است.', 'flavor' ); ?></p></div></div>
 <?php if ( ! $eligible ) : ?><div class="flavor-ui-empty"><?php \Flavor\UI::icon( 'calendar', 42 ); ?><h2><?php esc_html_e( 'رزرو آنلاین میز در دسترس نیست.', 'flavor' ); ?></h2><p><?php esc_html_e( 'برای این مجموعه شعبهٔ رزروپذیر با میز فعال معرفی نشده است. از منو یا راه‌های تماس استفاده کنید.', 'flavor' ); ?></p><a class="flavor-btn flavor-btn--primary" href="<?php echo esc_url( \Flavor\UI::url( 'menu' ) ); ?>"><?php esc_html_e( 'دیدن منو', 'flavor' ); ?></a><a class="flavor-btn flavor-btn--outline" href="<?php echo esc_url( \Flavor\UI::url( 'contact' ) ); ?>"><?php esc_html_e( 'هماهنگی تلفنی', 'flavor' ); ?></a></div>
 <?php else : ?>
 <div class="flavor-res-layout"><form id="flavor-res-form" class="flavor-checkout flavor-res-card" hidden>
  <section aria-labelledby="flavor-res-step-1"><h2 id="flavor-res-step-1"><span>۱</span><?php esc_html_e( 'شعبه و مهمان‌ها', 'flavor' ); ?></h2><div class="flavor-ui-grid-2"><div class="flavor-ui-field"><label for="flavor-res-branch"><?php esc_html_e( 'شعبه', 'flavor' ); ?></label><select id="flavor-res-branch" required></select></div><div class="flavor-ui-field"><label for="flavor-res-party"><?php esc_html_e( 'تعداد مهمان', 'flavor' ); ?></label><input type="number" id="flavor-res-party" value="2" min="1" max="20" required /></div></div><div class="flavor-ui-field"><label for="flavor-res-section"><?php esc_html_e( 'ترجیح بخش', 'flavor' ); ?></label><select id="flavor-res-section"><option value=""><?php esc_html_e( 'هر بخشِ دارای ظرفیت', 'flavor' ); ?></option></select></div></section>
  <section aria-labelledby="flavor-res-step-2"><h2 id="flavor-res-step-2"><span>۲</span><?php esc_html_e( 'روز و ساعت', 'flavor' ); ?></h2><div class="flavor-cal" id="flavor-cal"><div class="flavor-cal__nav"><button type="button" id="flavor-cal-prev" class="flavor-ui-icon-button" aria-label="<?php esc_attr_e( 'ماه قبل', 'flavor' ); ?>">‹</button><strong id="flavor-cal-title"></strong><button type="button" id="flavor-cal-next" class="flavor-ui-icon-button" aria-label="<?php esc_attr_e( 'ماه بعد', 'flavor' ); ?>">›</button></div><div class="flavor-cal__week" id="flavor-cal-week"></div><div class="flavor-cal__grid" id="flavor-cal-grid"></div></div><p class="flavor-ui-note" id="flavor-res-selection" role="status"><?php esc_html_e( 'ابتدا روز موردنظر را انتخاب کنید.', 'flavor' ); ?></p><div id="flavor-res-slots" class="flavor-slots" role="group" aria-label="<?php esc_attr_e( 'ساعت‌های قابل رزرو', 'flavor' ); ?>" aria-live="polite"></div></section>
  <section aria-labelledby="flavor-res-step-3"><h2 id="flavor-res-step-3"><span>۳</span><?php esc_html_e( 'اطلاعات هماهنگی', 'flavor' ); ?></h2><div class="flavor-ui-grid-2"><div class="flavor-ui-field"><label for="flavor-res-name"><?php esc_html_e( 'نام', 'flavor' ); ?></label><input type="text" id="flavor-res-name" autocomplete="name" maxlength="100" required /></div><div class="flavor-ui-field"><label for="flavor-res-mobile"><?php esc_html_e( 'موبایل', 'flavor' ); ?></label><input type="tel" id="flavor-res-mobile" autocomplete="tel" inputmode="tel" dir="ltr" required maxlength="16" placeholder="09xxxxxxxxx" /></div></div><div class="flavor-ui-field"><label for="flavor-res-note"><?php esc_html_e( 'نیاز یا توضیح تکمیلی', 'flavor' ); ?><span class="flavor-ui-required"><?php esc_html_e( ' (اختیاری)', 'flavor' ); ?></span></label><textarea id="flavor-res-note" rows="2" maxlength="200"></textarea></div></section>
  <p class="flavor-checkout__err" id="flavor-res-err" role="alert" tabindex="-1" hidden></p><p class="flavor-ui-success" id="flavor-res-ok" role="status" tabindex="-1" hidden></p><button type="submit" class="flavor-btn flavor-btn--primary flavor-btn--full"><?php esc_html_e( 'ارسال درخواست رزرو', 'flavor' ); ?><?php \Flavor\UI::icon( 'arrow', 18 ); ?></button>
 </form><aside class="flavor-res-guide flavor-ui-panel"><span class="flavor-account-login__mark" aria-hidden="true"><?php \Flavor\UI::icon( 'calendar', 30 ); ?></span><h2><?php esc_html_e( 'پیش از انتخاب زمان', 'flavor' ); ?></h2><ul><li><?php esc_html_e( 'تقویم شمسی است؛ تاریخ درخواست به قالب موردنیاز سرور تبدیل می‌شود.', 'flavor' ); ?></li><li><?php esc_html_e( 'تغییر تعداد یا بخش، ساعت قبلی را پاک و ظرفیت را دوباره بررسی می‌کند.', 'flavor' ); ?></li><li><?php esc_html_e( 'درخواست خاص یا حساسیت غذایی را پیش از مراجعه با مجموعه هماهنگ کنید.', 'flavor' ); ?></li><li><?php esc_html_e( 'وضعیت رزرو از پاسخ سرور اعلام می‌شود؛ زمان و ظرفیت تضمین نمایشی نیستند.', 'flavor' ); ?></li></ul><a class="flavor-ui-text-link" href="<?php echo esc_url( \Flavor\UI::url( 'contact' ) ); ?>"><?php esc_html_e( 'راه‌های تماس', 'flavor' ); ?><?php \Flavor\UI::icon( 'arrow', 17 ); ?></a></aside></div>
 <noscript><div class="flavor-ui-empty"><h2><?php esc_html_e( 'برای ظرفیت زنده، JavaScript لازم است.', 'flavor' ); ?></h2><p><?php esc_html_e( 'بدون آن، درخواست رزرو خودکار ارسال نمی‌شود. برای هماهنگی با مجموعه تماس بگیرید.', 'flavor' ); ?></p><a class="flavor-btn flavor-btn--outline" href="<?php echo esc_url( \Flavor\UI::url( 'contact' ) ); ?>"><?php esc_html_e( 'هماهنگی تلفنی', 'flavor' ); ?></a></div></noscript>
 <?php endif; ?>
</div>
