<?php
/** Juice Bar — Limo; complete one-click content and art direction. @package Flavor */
defined( 'ABSPATH' ) || exit;

return array(
	'slug'        => 'juice-bar',
	'title'       => 'آبمیوه و اسموتی — لیمو',
	'site_title'  => 'لیمو',
	'tagline'     => 'آبمیوه و اسموتی تازه؛ ساده، رنگی، خوش‌طعم',
	'hero_title'  => 'یک جرعه تازگی، یک روز پرانرژی.',
	'hero_text'   => 'میوهٔ تازهٔ فصل، ترکیب‌های خوش‌طعم و آبگیری پس از سفارش. از اسموتی سبز تا یک کاسهٔ رنگی، انتخاب امروزت را پیدا کن.',
	'about'       => 'لیمو از یک ایدهٔ ساده شروع شد: طعم خوب به مواد پیچیده نیاز ندارد. میوه‌ها را هر روز انتخاب می‌کنیم، ترکیب‌ها را با دقت می‌سازیم و نوشیدنی‌ات را بعد از سفارش آماده می‌کنیم. رسپی‌ها روشن‌اند؛ اگر شیر گیاهی می‌خواهی، شیرینی کمتر دوست داری یا به ماده‌ای حساسیت داری، پیش از سفارش با ما در میان بگذار.',
	'branch_name' => 'بار میوه لیمو — یوسف‌آباد',
	'city'        => 'تهران',
	'phone'       => '02188004567',
	'address'     => 'تهران، یوسف‌آباد، خیابان اسدآبادی، پلاک ۳۲',
	'order_modes' => array( 'takeaway', 'delivery' ),
	'tables'      => 0,
	'theme_mods'  => array(
		'flavor_hero_badge'     => 'تازه از طبیعت، آماده برای تو',
		'flavor_hero_style'     => 'split',
		'flavor_hero_cta'       => 'انتخاب نوشیدنی',
		'flavor_hero_cta2'      => 'قصهٔ لیمو',
		'flavor_header_topbar'  => 'هر روز از ساعت ۸ تا ۲۲  ·  میوهٔ فصل، آبگیری تازه، بسته‌بندی سرد',
		'flavor_phone'          => '02188004567',
		'flavor_address'        => 'تهران، یوسف‌آباد، خیابان اسدآبادی، پلاک ۳۲',
		'flavor_hours'          => 'همه‌روزه، ۸ صبح تا ۲۲',
		'flavor_featured_title' => 'امروز چه رنگی می‌نوشی؟',
	),
	'navigation' => array(
		array( 'label' => 'منوی رنگی', 'anchor' => '#menu' ),
		array( 'label' => 'قصهٔ لیمو', 'anchor' => '#story' ),
		array( 'label' => 'پرسش‌ها', 'anchor' => '#faq' ),
		array( 'label' => 'پیدایمان کن', 'anchor' => '#visit' ),
	),
	'categories' => array( 'آبمیوهٔ تازه' => 'fresh-juices', 'اسموتی' => 'smoothies', 'کاسهٔ میوه' => 'fruit-bowls', 'شات تازه' => 'fresh-shots' ),
	'category_images' => array( 'fresh-juices' => 'category-fresh.jpg', 'smoothies' => 'category-smoothies.jpg', 'fruit-bowls' => 'category-bowls.jpg', 'fresh-shots' => 'category-shots.jpg' ),
	'testimonials' => array(), // No invented customer ratings on the landing page.
	'items' => array(
		flavor_demo_item( 'پرتقالِ تازه', 'پرتقال آبگیری‌شده، بدون شکر افزوده؛ لیوان ۳۵۰ میلی‌لیتری', 89000, 'fresh-juices', array( 'prep' => 5, 'image' => 'category-fresh.jpg', 'dietary' => array( 'vegan' ) ) ),
		flavor_demo_item( 'اسموتی سبزِ لیمو', 'کیوی، خیار، سیب سبز و نعنا؛ طعمی تازه و متعادل', 145000, 'smoothies', array( 'prep' => 7, 'image' => 'product-green.jpg', 'dietary' => array( 'vegan' ) ) ),
		flavor_demo_item( 'توت‌فرنگی و موز', 'توت‌فرنگی، موز و شیر؛ امکان انتخاب شیر جو دوسر', 155000, 'smoothies', array( 'prep' => 7, 'image' => 'category-smoothies.jpg', 'allergens' => array( 'milk' ) ) ),
		flavor_demo_item( 'کاسهٔ آکای و گرانولا', 'پورهٔ آکای، موز، توت‌فرنگی، بلوبری، گرانولا و چیا', 225000, 'fruit-bowls', array( 'prep' => 10, 'image' => 'category-bowls.jpg', 'dietary' => array( 'vegan' ), 'allergens' => array( 'gluten', 'nuts' ) ) ),
		flavor_demo_item( 'هویج و پرتقال', 'آب هویج و پرتقال تازه با مقدار کمی زنجبیل', 105000, 'fresh-juices', array( 'prep' => 5, 'image' => 'category-fresh.jpg', 'dietary' => array( 'vegan' ) ) ),
		flavor_demo_item( 'اسموتی بریِ گیاهی', 'توت‌فرنگی، موز و شیر جو دوسر؛ بدون شیر لبنی', 165000, 'smoothies', array( 'prep' => 7, 'image' => 'category-smoothies.jpg', 'dietary' => array( 'vegan' ), 'allergens' => array( 'gluten' ) ) ),
		flavor_demo_item( 'کاسهٔ میوهٔ فصل', 'آکای و انتخاب میوه‌های روز با گرانولای ترد؛ ترکیب فصل متغیر است', 195000, 'fruit-bowls', array( 'prep' => 8, 'image' => 'category-bowls.jpg', 'dietary' => array( 'vegan' ), 'allergens' => array( 'gluten', 'nuts' ) ) ),
		flavor_demo_item( 'شات زنجبیل و لیمو', 'آب لیموی تازه، زنجبیل و سیب؛ بطری ۶۰ میلی‌لیتری', 65000, 'fresh-shots', array( 'prep' => 4, 'image' => 'category-shots.jpg', 'dietary' => array( 'vegan' ) ) ),
	),
	'landing' => array(
		'wordmark'        => 'LIMO / FRESH DAILY',
		'brand_caption'   => 'آبمیوه و اسموتی تازه',
		'brand_icon'      => 'leaf',
		'eyebrow'         => 'تازه از طبیعت، آماده برای تو',
		'hero_accent'     => 'یک روز پرانرژی.',
		'hero_alt'        => 'بطری‌های آبمیوه سبز، پرتقالی و اسموتی توت‌فرنگی کنار میوهٔ تازه',
		'primary_action'  => 'menu',
		'primary_label'   => 'انتخاب نوشیدنی',
		'primary_icon'    => 'glass',
		'mobile_label'    => 'سفارش تازه',
		'secondary_label' => 'قصهٔ لیمو',
		'hero_caption'    => 'هر رنگ، یک طعم تازه',
		'hero_caption_tag'=> 'از منوی امروز',
		'perks'           => array( 'آبگیری پس از سفارش', 'بسته‌بندی سرد', 'انتخاب شیر گیاهی' ),
		'steps'           => array(
			array( 'title' => 'میوهٔ فصل، هر روز', 'text' => 'انتخاب روزانه؛ طعم واقعی از همین‌جا شروع می‌شود.', 'icon' => 'leaf' ),
			array( 'title' => 'برای تو آماده می‌شود', 'text' => 'نوشیدنی‌ات را بعد از ثبت سفارش ترکیب می‌کنیم.', 'icon' => 'glass' ),
			array( 'title' => 'خنک تا آخرین جرعه', 'text' => 'بسته‌بندی مناسب برای تحویل حضوری یا ارسال.', 'icon' => 'truck' ),
		),
		'menu_eyebrow'    => 'منوی رنگی لیمو',
		'menu_title'      => 'امروز چه رنگی می‌نوشی؟',
		'menu_text'       => 'میوه‌ها، ترکیب‌ها و یک عالمه انتخاب خوش‌طعم.',
		'story_eyebrow'   => 'قصهٔ کوتاه ما',
		'story_title'     => 'مواد ساده. طعم واقعی.',
		'story_alt'       => 'اسموتی و آبمیوهٔ تازه روی پیشخوان بار میوه',
		'story_caption'   => 'تازگی، از انتخاب میوه تا آخرین جرعه.',
		'story_values'    => array( 'ترکیب‌های روشن و مواد قابل‌شناختن', 'آماده‌سازی بعد از سفارش، نه از قبل', 'امکان هماهنگی رسپی با سلیقهٔ تو' ),
		'story_link'      => 'طعم دلخواهت را پیدا کن',
		'feature_eyebrow' => 'یک انتخاب کوچک و پرطعم',
		'feature_title'   => 'کوچک، تند، دوست‌داشتنی.',
		'feature_text'    => 'شات زنجبیل و لیمو؛ یک ترکیب جمع‌وجور از آب لیموی تازه، سیب و زنجبیل. بدون ادعای معجزه؛ فقط یک طعم زنده و متفاوت.',
		'feature_label'   => 'کشف شات‌های تازه',
		'faq_title'       => 'سؤالی قبل از اولین جرعه؟',
		'faq_text'        => 'ترکیب‌ها را شفاف می‌گوییم تا انتخاب راحت‌تر شود.',
		'faq' => array(
			array( 'question' => 'به آبمیوه‌ها شکر اضافه می‌کنید؟', 'answer' => 'آبمیوه‌های تازهٔ این منو بدون شکر افزوده آماده می‌شوند و قند طبیعی میوه دارند. ترکیبات هر اسموتی در توضیح محصول آمده است؛ برای تغییر شیرینی قبل از سفارش با ما هماهنگ کنید.' ),
			array( 'question' => 'شیر گیاهی و انتخاب بدون لبنیات دارید؟', 'answer' => 'اسموتی بریِ گیاهی با شیر جو دوسر و اسموتی سبز بدون لبنیات آماده می‌شوند. برای تغییر رسپی سایر نوشیدنی‌ها با ما تماس بگیرید؛ امکان تهیه به موجودی روز بستگی دارد.' ),
			array( 'question' => 'اگر حساسیت غذایی داشته باشم چه کنم؟', 'answer' => 'گرانولا و شیرها ممکن است حاوی گلوتن، مغزها یا لبنیات باشند. تجهیزات مشترک‌اند؛ پیش از ثبت سفارش حساسیت خود را تلفنی اعلام کنید. نبود یک ماده در رسپی، به معنی نبود تماس متقاطع نیست.' ),
			array( 'question' => 'چطور سفارش بدهم و دریافت کنم؟', 'answer' => 'از منوی کامل، محصول و روش دریافت را انتخاب کنید. محدودهٔ ارسال، هزینه و زمان تخمینی در فرایند سفارش مشخص می‌شود. زمان آماده‌سازی روی کارت‌ها، زمان تحویل پیک نیست.' ),
		),
		'visit_eyebrow' => 'از پیشخوان ما تا روز تو',
		'visit_title'   => 'حالا نوبت یک جرعه تازگی است.',
		'hours'         => 'همه‌روزه، ۸ صبح تا ۲۲',
	),
);
